name: Deploy to ECS

on:
  push:
    paths-ignore:
      - "agents/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build, Push to ECR, and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::471112658624:role/github-role
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install AWS Copilot
      run: |
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/download/v1.34.0/copilot-linux-v1.34.0
          chmod +x copilot
          sudo mv copilot /usr/local/bin/

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Deploy using AWS Copilot
      run: |
          copilot init --app hopelogdev --svc backend --type "Backend Service" --dockerfile ./Dockerfile --port 80 || echo "App already initialized."
          copilot deploy --env development