name: Deploy to ECS

on:
    push:
      paths:
        - "**.py" 
      branches:
        - main 
    workflow_dispatch:
jobs:
  deploy:
    name: Build, Push to ECR, and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::471112658624:role/github-role
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image
      run: |
        ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/build-with-ai-hackaton-be
        docker buildx build \
                --platform linux/amd64 \
                --tag $ECR_URI:latest \
                --push .

